baseURL = "https://raghuugare.github.io"
languageCode = "en-us"
title = "Biscuits in Tea...!"
theme = "minimal"
disqusShortname = "raghu-ugare-github"# delete this to disable disqus comments
googleAnalytics = "UA-58142785-1"
enableRobotsTXT = false
enableEmoji = true

[blackfriday]
    hrefTargetBlank = true

[params]
    author = "Raghu Ugare"
    description = ""
    githubUsername = "raghuugare"
    accent = "#ff0049" # "#009800"
    showBorder = true
    backgroundColor = "white"
    font = "Aleo" # "Scope One" # "Fanwood Text" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    linenos="inline"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2

[[menu.main]]
   url = "/about/"
   name = "About"
   weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:raghu.ugare@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/raghuugare/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/raghu_ugare/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/rugare/"
    name = "linkedin"
    weight = 4

[[menu.icon]]
    url = "https://www.stackoverflow.com/users/1103825/fritz"
    name = "stack-overflow"
    weight = 5
